name: device_security_scan
description: Flutter plugin for detecting rooted or jailbroken devices, developer options, USB debugging, emulators, debuggers, and other security indicators.
version: 0.1.0

homepage: https://github.com/JitendraYadavCdac/device_security_scan
repository: https://github.com/JitendraYadavCdac/device_security_scan
issue_tracker: https://github.com/JitendraYadavCdac/device_security_scan/issues

topics:
  - security
  - root-detection
  - jailbreak
  - android
  - ios

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: '>=3.10.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  plugin:
    platforms:
      android:
        package: com.jitendrayadav.device_security_scan
        pluginClass: DeviceSecurityCheckPlugin
      ios:
        pluginClass: DeviceSecurityCheckPlugin